---
- include_tasks: bootstrap_aio.yaml
  tags:
  - first_run
  - bootstrap_aio

- name: copy our custom user variables
  become: yes
  copy:
    src: templates/user_local_variables.yaml
    dest: /etc/openstack_deploy/user_local_variables.yml
    owner: root
    group: root
    mode: 0644
  tags:
    - always

- include_tasks: prerun_hacks.yaml
  tags:
  - always

- include_tasks: service_configs.yaml
  tags:
  - install_additional_services

- include_tasks: create_containers.yaml
  tags:
  - create_containers
  - install_additional_services

- name: setup-hosts
  become: yes
  command: /usr/local/bin/openstack-ansible setup-hosts.yml
  args:
    chdir: /opt/openstack-ansible/playbooks
  tags:
    - first_run
    - setup_hosts

- name: setup-infrastructure
  become: yes
  command: /usr/local/bin/openstack-ansible setup-infrastructure.yml
  args:
    chdir: /opt/openstack-ansible/playbooks
  tags:
    - first_run
    - setup_infrastructure

- name: setup-openstack
  become: yes
  command: /usr/local/bin/openstack-ansible setup-openstack.yml
  args:
    chdir: /opt/openstack-ansible/playbooks
  tags:
    - first_run
    - setup_openstack

- include_tasks: haproxy_config.yaml
  tags:
    - haproxy_config
    - install_additional_services
  
- include_tasks: additional_services.yaml
  tags:
    - install_additional_services

- include_tasks: reconfigure_services.yaml
  tags:
    - reconfigure_services
    - reconfigure_manila
    - manila-config