---
- include_tasks: bootstrap_aio.yaml
  tags:
  - first_run
  - bootstrap_aio
    
- include_tasks: prerun_hacks.yaml
  tags:
  - always

# Put all additional services BELOW this line

- include_tasks: manila.yaml
  tags:
  - install_manila

# Put all additional services ABOVE this line

- include_tasks: create_containers.yaml
  tags:
  - create_containers

- name: setup-hosts
  become: yes
  command: /usr/local/bin/openstack-ansible setup-hosts.yml
  args:
    chdir: /opt/openstack-ansible/playbooks
  tags:
    - first_run
    - setup_hosts

- name: setup-infrastructure
  become: yes
  command: /usr/local/bin/openstack-ansible setup-infrastructure.yml
  args:
    chdir: /opt/openstack-ansible/playbooks
  tags:
    - first_run
    - setup_infrastructure

- name: setup-openstack
  become: yes
  command: /usr/local/bin/openstack-ansible setup-openstack.yml
  args:
    chdir: /opt/openstack-ansible/playbooks
  tags:
    - first_run
    - setup_openstack
  
- name: run os-manila-install playbook
  become: yes
  command: openstack-ansible playbooks/os-manila-install.yml
  args:
    chdir: /opt/openstack-ansible
  tags:
    - install_manila