---
- include_tasks: bootstrap_aio.yaml
  tags:
  - first_run
  - bootstrap_aio

- name: copy our custom user variables
  become: yes
  copy:
    src: "{{ item }}"
    dest: /etc/openstack_deploy/
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - roles/osa/templates/user_variables_*.yml
  tags:
    - always

- include_tasks: prerun_hacks.yaml
  tags:
  - always

- include_tasks: haproxy_config.yaml
  tags:
    - haproxy_config
    - install_additional_services

- include_tasks: service_configs.yaml
  tags:
  - install_additional_services

- name: setup-hosts
  become: yes
  command: /usr/local/bin/openstack-ansible setup-hosts.yml
  vars:
    openstack_hosts_centos_mirror_url: 'http://archive.linux.duke.edu/centos/'
    openstack_hosts_enable_yum_fastestmirror: false
  args:
    chdir: /opt/openstack-ansible/playbooks
  tags:
    - first_run
    - setup_hosts

- name: setup-infrastructure
  become: yes
  command: /usr/local/bin/openstack-ansible setup-infrastructure.yml
  vars:
    openstack_hosts_centos_mirror_url: 'http://archive.linux.duke.edu/centos/'
    openstack_hosts_enable_yum_fastestmirror: false
  args:
    chdir: /opt/openstack-ansible/playbooks
  tags:
    - first_run
    - setup_infrastructure

- name: setup-openstack
  become: yes
  command: /usr/local/bin/openstack-ansible setup-openstack.yml
  args:
    chdir: /opt/openstack-ansible/playbooks
  tags:
    - first_run
    - setup_openstack

- include_tasks: create_containers.yaml
  vars:
    baseurl: 'http://archive.linux.duke.edu/epel/'
    openstack_hosts_centos_mirror_url: 'http://archive.linux.duke.edu/epel/'
    openstack_hosts_enable_yum_fastestmirror: no
    lxc_centos_epel_mirror: 'http://archive.linux.duke.edu/epel/'
    lxc_centos_epel_gpg_key: 'http://archive.linux.duke.edu/epel/RPM-GPG-KEY-EPEL-7'
  tags:
  - create_containers
  - install_additional_services

- include_tasks: additional_services.yaml
  tags:
    - install_additional_services

- include_tasks: reconfigure_services.yaml
  tags:
    - reconfigure_services
    - reconfigure_manila
    - manila-config