---
- name: remove dragonflow (should only run on Rocky)
  become: yes
  lineinfile:
    path: /etc/ansible/roles/os_neutron/vars/main.yml
    regex: '^  - dragonflow'
    state: absent
  tags:
    - always