---
- hosts: all
  vars:
    ansible_python_interpreter: "/usr/bin/python"
  remote_user: vagrant
  roles:
    - common
  tags:
    - first_run

- hosts: aio
  vars:
    ansible_python_interpreter: "/usr/bin/python"
  remote_user: vagrant
  roles:
    - osa
      
