---
- name: add openstack-ansible conf.d file for ceph
  become: yes
  copy:
    src: templates/conf.d/ceph.yml
    dest: /etc/openstack_deploy/conf.d/ceph.yml
    owner: root
    group: root
    mode: 0644
  tags:
    - install_ceph

- name: replace inventory/env.d/ceph.yml
  copy:
    src: ceph/inventory/env.d/ceph.yml
    dest: /opt/openstack-ansible/inventory/env.d/ceph.yml
    mode: '0664'
  tags:
    - install_ceph