---
- name: configure manila
  become: yes
  copy:
    remote_src: yes
    src: /opt/openstack-ansible/etc/openstack_deploy/conf.d/manila.yml.aio
    dest: /etc/openstack_deploy/conf.d/manila.yml
    owner: root
    group: root
    mode: 0644
  tags:
    - install_manila

- name: (hack to fix broken build) drop missing redhat vars file
  become: yes
  copy:
    src: files/manila/redhat.vars.yml
    dest: /etc/ansible/roles/os_manila/vars/redhat.yml
    owner: root
    group: root
    mode: 0644
  tags:
    - install_manila
